server:
  port: 9092

eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    register-with-eureka: true
    fetchRestistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka
  server:
    wait-time-in-ms-when-sync-empty: 3000
      
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: excalibur
    platform: mysql
    url: jdbc:mysql://localhost/excalibur_finance?verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: excalibur
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: create
    show-sql: true